# -*- coding: utf-8 -*-
"""class_ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132FZUrkhNTi6di4XBfxGc6yxO0UdymCj
"""

class User():
  def __init__(self, first_name, last_name, age, course, country):
    self.first_name = first_name
    self.last_name = last_name
    self.age = age
    self.course = course
    self.country = country

  def describe_user(self):
    print("\n\nUser Name is: \t\t" + self.first_name.title() + " " + self.last_name.title())
    print("User age is: \t\t" + str(self.age))
    print("Course subscribed to: \t" + self.course.title())
    print("User comes from: \t" + self.country.title())

  def greet_user(self):
    print("\nHello " + self.first_name.title() + " " + self.last_name.title() + "!")

user_1 = User('remijeous', 'visu', 32, 'python', 'india')
user_1.describe_user()
user_1.greet_user()

user_2 = User('nivetha', 'remijeous', 26, 'java', 'india')
user_2.describe_user()
user_2.greet_user()