# -*- coding: utf-8 -*-
"""excercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGDDlx6xp3XcjyxdFq6Srw7Ue-JiywXd
"""

def modify_list_fruits(fruits):
    fruit_set = set(fruits)
    fruit_set.add("pear")
    fruit_set.remove("apple")
    fruit_list = list(fruit_set)
    return fruit_list[1]

fruits = ["apple", "banana", "orange"]

print(modify_list_fruits(fruits))

fruits = ["apple", "banana", "orange"]
fruits.append('pear')
print(fruits)

for value in range(1,5):
  print(value)

numbers = list(range(1,6))
print(numbers)

odd_numbers_3 = list(range(2,51,3))
print(odd_numbers_3)